version: "3.7"
services:
  mysql-service:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=airplane
    container_name: mysql-service
  web-service:
    restart: on-failure
    depends_on:
      - mysql-service
    build:
      context: .
      dockerfile: Dockerfile
    image: web-app-air:v1
    ports:
      - "8086:8086"
    links:
      - mysql-service
    container_name: web-service
